;;; lang-nzsql.el ---

;; netezza

(require 'generic-x)

(defface c3-face-1 
      '((t (:foreground "#FF0000")))
      "red")

(define-generic-mode 'nzplan-mode
  '("!!") ;; comment
  '("HashNode" "ProjectNode" "ScanNode" "RestrictNode" "DownloadTableNode"
    "DoneNode" "HashJoinNode" "DropTableNode" "InsertNode" "InsertStatsNode"
    "ReturnNode" "ScanPrepNode" "CreateTempTableNode" "ScanBlockCountNode"
    "SaveTempNode" "ExistsJoinNode" "StreamAppendNode") ;; keywords
  '(("%{\\([A-Z_]+\\)}" 1 font-lock-variable-name-face)
    ("\\b[0-9]*\\b" . font-lock-constant-face)
    ("spu" . font-lock-type-face) ;; things executed on SPU
    ("dbs" . 'c3-face-1)) ;; things executed on HOST highlithed in RED
  '("\\.nzplan$") ;; files for which to activate this mode
  nil ;; other functions to call
  "A mode for Netezza plan files")
  
(define-generic-mode 'nzsql-mode
  '("--")
  '("ABORT" "DEC" "LEADING" "RESET" "ADMIN" "REUSE" "AGGREGATE" "ALIGN" "DEFAULT" "LIMIT" "ROWS" "COMMIT"
"INSERT" "DEFERRABLE" "DEFERRED" "LISTEN" "ROWSETLIMIT" "ALLOCATE" "ASC" "DESC" "LOAD" "RULE" "ANALYSE" "DISTINCT" "LOCAL" "SEARCH" 
"ANALYZE" "DISTRIBUTE" "ORGANIZE" "LOCK" "SELECT" "DO" "MATERIALIZED" "SEQUENCE" "MINUS" "AS" "END" "MOVE" "SETOF"
"EXCEPT" "NATURAL" "SHOW" "BETWEEN" "EXCLUDE" "BINARY" "NEW" "BIT" "EXPLAIN" "SYSTEM" "BOTH"
"EXPRESS" "NOTNULL" "TABLE" "EXTEND" "NULL" "THEN" "CASE" "WHEN" "EXTERNAL" "NULLIF" "TIES" "DROP"
"NULLS" "FALSE" "CHECK" "FIRST" "TO" "CLUSTER" "TRAILING" "FOLLOWING" "OFF" "TRANSACTION"
"COLLATE" "OFFSET" "TRIGGER" "COLLATION" "FOREIGN" "OLD" "COLUMN" "FROM" "ON" "TRUE" "RENAME"
"CONSTRAINT" "ONLINE" "UNBOUNDED" "COPY" "FUNCTION" "ONLY" "UNION" "GENSTATS" "UNIQUE" "CURRENT" "GLOBAL"
"ORDER" "BY" "USER" "GROUP" "OTHERS" "USING" "HAVING" "OUT" "VACUUM" "IDENTIFIER_CASE" "OVER" "VERBOSE"
"VERSION" "INDEX" "PARTITION" "VIEW" "INITIALLY" "POSITION" "DELETE" "UPDATE" "SET" "NEXT" "VALUE" "VALUES" "TRUNCATE" "COMMENT"
"PRECEDING" "WHERE" "INOUT" "PRECISION" "WITH" "INTERSECT" "PRESERVE" "WRITE" "DEALLOCATE"
"PRIMARY" "RESET" "INTO" "REUSE" "ROWID" "CREATEXID" "DELETEXID" "DATASLICEID" "CREATE" "ALTER"
"PROCEDURE" "DATABASE" "GRANT" "REVOKE" "RETURN" "RETURNS" "LANGUAGE" "NZPLSQL" "DECLARE" "BEGIN" "EXCEPTION"
"EXEC" "EXECUTE" "IMMEDIATE" "BEGIN_PROC" "END_PROC" "RAISE" "NOTICE" "REPLACE" "CALL" "CALLER" "OWNER"
"CONSTANT" "EXIT" "ROLLBACK" "KEY" "TEMP" "SYNONYM" "GENERATE" "STATISTICS" "FINAL" "GROOM" 
"LIBRARY" "HOST" "SPU" "OBJECT" "REFERENCES" "SECURITY" "LEVEL" "CATEGORY" "COHORT" "PASSWORD" "LABEL"
"DATAOBJECT" "MAXERRORS" "DELIMITER" "DATESTYLE" "QUOTEDVALUE" "NULLVALUE" "ESCAPECHAR"
"CRINSTRING" "TRUNCSTRING" "DATEDELIM" "TIMESTYLE" "TIMEDELIM" "BOOLSTYLE" "CTRLCHARS"
"LOGDIR" "MAXROWS" "REQUIREQUOTES" "IGNOREZERO" "TIMEEXTRAZEROS" "Y2BASE" "FILLRECORD"
"FORMAT" "COMPRESS" "ENCODING" "REMOTESOURCE" "SOCKETBUFSIZE" "SKIPROWS" "CASCADE" "RESTRICT" "ACTION" "NO" "MODIFY"
"GROUPING" "SETS" "CUBE" "ROLLUP" "PLANFILE" "SCHEMA" "CATALOG")
  '("IF" "ELSE" "ELSIF" "COALESCE" "CAST" "EXTRACT" "DATE_PART" "NVL" "NVL2" "DECODE" "LOOP" "FOR"
"TO_CHAR" "TO_DATE" "TO_NUMBER" "TO_TIMESTAMP" "EPOCH" "YEAR" "YEARS" "QUARTER" "MONTH" "MONTHS" "WEEK" "DAY" 
"DAYS" "DOW" "DOY" "HOUR" "HOURS" "MINUTE" "MINUTES" "SECOND" "SECONDS" "MILLISECOND" "MILLISECONDS" 
"MICROSECOND" "MICROSECONDS" "COUNT" "SUM" "MAX" "MIN" "AVG" "TRIM" "POSITION" "SUBSTRING" "CHARACTER_LENGTH"
"DLE_DST" "LE_DST" "NYSIIS" "DBL_MP" "PRI_MP" "SEC_MP" "SCORE_MP" "CURRENT_CATALOG" "CURRENT_DATE" "CURRENT_TIME"
"CURRENT_TIMESTAMP" "CURRENT_USER" "CURRENT_DB" "CURRENT_SID" "CURRENT_USERID" "CURRENT_USEROID" "SESSION_USER"
"ACOS" "ASIN" "ATAN" "ATAN2" "COS" "COT" "DEGREES" "PI" "RADIANS" "SIN" "TAN" "RANDOM" "SETSEED"
"ABS" "CEIL" "EXP" "FACTORIAL" "FLOOR" "LN" "LOG" "MOD" "POW" "ROUND" "SIGN" "SQRT" "TRUNC" "INTNAND"
"INTNOR" "INTNXOR" "INTNNOT" "INTNSHL" "INTNSHR" "ASCII" "BTRIM" "CHR" "INITCAP" "INSTR" "LENGTH" "LOWER" "LPAD"
"LTRIM" "REPEAT" "RPAD" "RTRIM" "STRPOS" "SUBSTR" "TRANSLATE" "UPPER" "UNICHR" "UNICODE"
"ADD_MONTHS" "AGE" "DATE_PART" "DATE_TRUNC" "EXTRACT" "LAST_DAY" "MONTHS_BETWEEN"
"NEXT_DAY" "NOW" "OVERLAPS" "TIMEOFDAY" "ISFALSE" "ISNOTFALSE" "ISTRUE" "ISNOTTRUE" "VERSION" "GET_VIEWDEF"
"SQLERRM" "ROW_COUNT" "LAST_OID" "FOUND" "REVERSE" "DATETIME" "STDDEV" "STDDEV_POP" "STDDEV_SAMP" "VARIANCE"
"VAR_POP" "VAR_SAMP" "ROW_NUMBER" "RANK" "DENSE_RANK" "LEAD" "LAG" "FIRST_VALUE" "LAST_VALUE" "CURRENT_SCHEMA" 
"CURRENT_TX_SCHEMA" "CURRENT_SCHEMAID" "CURRENT_TX_SCHEMAID" "CURRENT_TX_PATH" "DB_ENCODING"
"SEARCH_PATH" "CHARCODES" "CHAR_LENGTH" "COMBINE_LABEL" "CURRENT_DBID" "CURRENT_PATH" "DCEIL" "DEXP" "DFLOOR"
"DLOG1" "DLOG10" "DPOW" "DROUND" "DSQRT" "DTRUNC" "FPOW" "GETDATABASEENCODING" "INT_MONTHS_BETWEEN" "NVARCHARCAT"
"QUOTE_IDENT" "QUOTE_LITERAL" "STRING_FROM_HEX" "STRING_TO_HEX" "TIMESTAMP_CMP" "TIMESTAMP_TO_LOCALTIME"
"UTF8CODES" "WIDTH_BUCKET" . font-lock-constant-face)
  '()
  '("\\.nzsql$")
  nil
  "A mode for Netezza sql")  
